### PR TITLE
Fixes micrate timestamp collisions

### PR DESCRIPTION
**Pull request by faustinoaq**
This PR does:

- Bugfix to group by index without missing versions with same timestamp.
- Add Amber Team to shard.yml
- Add version v0.4.0 (still requires to release tag `v0.4.0` because **`shards` doesn't detect new version without tag**

This Fix is already published on `v0.3.1`, based on `v0.3.0` because micrate master has some breaking changes.

Please see:  https://github.com/amberframework/micrate/releases/tag/v0.3.1

Fixes: #31

### CODE REVIEW

**Comment by faustinoaq** [comment]
These `breaking-changes` should be addressed before publishing micrate `v0.4.0`

[screenshot_20180501_035355](https://github.com/amberframework/micrate/compare/v0.3.0...master)

**Comment by robacarp** [comment]
@faustinoaq can you show me what this is doing? is it appending an incremental number to the end of the migration filename?

**Comment by robacarp** [comment]
As for the breaking changes that have been merged into master and aren't yet tagged as a release, I don't think we really have a choice but to up the version before releasing. Do you have a different idea?

**Comment by faustinoaq** [comment]
> can you show me what this is doing?

@robacarp , Yeah, this is sorting the files and applying a auxiliar index (based on `.sort` method) to avoid collisions on similar timestamps (filenames). This is already working fine on version v0.3.1 and fixed the Travis failures.

> is it appending an incremental number to the end of the migration filename?

No, is just a helper index.

> As for the breaking changes that have been merged into master and aren't yet tagged as a release, I don't think we really have a choice but to up the version before releasing. Do you have a different idea?

Yeah, definitively, those breaking changes require a new minor version (v0.4.0) and some changes on `amber db migrate` implementation.

I think we can merge this and use `v0.3.1` until we update migration implementation on amber

I already opened a tracking issue for this, see: https://github.com/amberframework/amber/issues/794

**Pull request closed without merging**
