### PR TITLE
Implement unconditional transactions

### LINKED ISSUE #11: Wrap migrations in a transaction by default
It would be nice to have micrate run migrations inside transactions by default. We should only find out if doing so would introduce a breaking change (in case somebody is already initialising a transaction outside micrate's code) or if crystal-db handles this case well for every adapter.

### PR DESCRIPTION
**Pull request by Serdnad**
In addition to minor cleanups like updating README references, this merge request makes all migrations run in a transaction by default, by wrapping all of the statements in each migration with a `Begin` and `Commit` block.

I've tested this on a Postgres setup, and the documentation for MySQL and SQLite both state support for these commands.

Admittedly, I'm not entirely sure what undesired effects there will be for people already writing transactions in their migration files. Fortunately, it seems like nested transactions are generally supported.

Even then, I imagine that most use cases aren't effected, and only serve to benefit from being automatically wrapped.

Fixes #11 .

### CODE REVIEW

**Comment by Serdnad** [comment]
Hmm, not easily, since the library doesn't currently run any tests on an actual DB.

**Comment by Serdnad** [comment]
Hey @drujensen , is this waiting on anything?

**Comment by pynixwang** [comment]
it also need an advisory lock to avoid multi migration process.

**Comment by Serdnad** [comment]
@pynixwang I agree that'd be a great addition, but that seems to me like a separate feature from this one. Also, it's database dependent.

**Comment by pynixwang** [comment]
> @pynixwang I agree that'd be a great addition, but that seems to me like a separate feature from this one. Also, it's database dependent, whereas this little change isn't.

it can be a simple file lock because sqlite don't support lock.

**Pull request merged**
